### ISSUE TITLE
want to cite this tool in article

### ISSUE THREAD

**Issue by sowptika** [moshi4/COGclassifier#1]
Dear Developers,
I have used this tool and worked well with me with no issues. I am writing here to know how should I cite this software in my research article. It will be great if you can share a link or citation details of this software.

Thank you
Sincerely,
Sowptika Pal

**Comment by moshi4** [comment]
> It will be great if you can share a link or citation details of this software.

As shown below, the suggested citation can be found from the repository top page.

![COGclassifier_toppage](https://user-images.githubusercontent.com/41852815/224754762-257fc874-f59d-44dc-a7b4-5fb1da0e1d13.png)

**Comment by sowptika** [comment]
Dear moshi4,
Thank you for your help.

Sincerely
Sowptika Pal
